name: CI (Coq, docker, dev)

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: all
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: dev
        ocaml_version: 4.05
        custom_script: |
          if ! command -v sudo &> /dev/null; then
            echo '::group::install sudo'
            su -c 'apt-get update -y'
            su -c 'apt-get install -y sudo'
            echo '::endgroup::'
          fi
          sudo chmod a+rw .
          echo '::group::install general dependencies'
          sudo apt-get update -y
          sudo apt-get install -y wget curl python python3
          eval $(opam env)
          echo '::endgroup::'
          echo '::remove-matcher owner=coq-problem-matcher::'
          etc/ci/github-actions-make.sh --warnings -j2 all
